type Household @aws_iam @aws_cognito_user_pools {
  name: String!
  owner: String
  people(filter: ModelPersonFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelPersonConnection
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Person @aws_iam @aws_cognito_user_pools {
  householdId: ID!
  household: Household
  owner: String
  displayName: String!
  role: PersonRole
  avatarUrl: String
  indicators(filter: ModelIndicatorFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelIndicatorConnection
  checkIns(filter: ModelCheckInFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelCheckInConnection
  events(filter: ModelEventFilterInput, sortDirection: ModelSortDirection, limit: Int, nextToken: String): ModelEventConnection
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Indicator @aws_iam @aws_cognito_user_pools {
  personId: ID!
  person: Person
  owner: String
  name: String!
  questionText: String
  polarity: IndicatorPolarity
  inputType: IndicatorInputType
  active: Boolean
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type CheckIn @aws_iam @aws_cognito_user_pools {
  personId: ID!
  person: Person
  owner: String
  occurredAt: AWSDateTime!
  answersJson: AWSJSON
  note: String
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

type Event @aws_iam @aws_cognito_user_pools {
  personId: ID!
  person: Person
  owner: String
  occurredAt: AWSDateTime!
  type: EventType
  title: String!
  description: String
  metadataJson: AWSJSON
  id: ID!
  createdAt: AWSDateTime!
  updatedAt: AWSDateTime!
}

enum PersonRole {
  child
  parent
  spouse
  self
  caregiver
  other
}

enum IndicatorPolarity {
  desired
  undesired
}

enum IndicatorInputType {
  boolean
  scale
  count
  duration
  text
}

enum EventType {
  note
  incident
  school
  medical
  sleep
  medication
  other
  interaction
  event
}

input AmplifyAIConversationTurnErrorInput {
  errorType: String!
  message: String!
}

input ModelStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelBooleanInput {
  ne: Boolean
  eq: Boolean
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
}

input ModelIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  attributeExists: Boolean
  attributeType: ModelAttributeTypes
  size: ModelSizeInput
}

input ModelSubscriptionStringInput {
  ne: String
  eq: String
  le: String
  lt: String
  ge: String
  gt: String
  contains: String
  notContains: String
  between: [String]
  beginsWith: String
  in: [String]
  notIn: [String]
}

input ModelSubscriptionIntInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
  in: [Int]
  notIn: [Int]
}

input ModelSubscriptionFloatInput {
  ne: Float
  eq: Float
  le: Float
  lt: Float
  ge: Float
  gt: Float
  between: [Float]
  in: [Float]
  notIn: [Float]
}

input ModelSubscriptionBooleanInput {
  ne: Boolean
  eq: Boolean
}

input ModelSubscriptionIDInput {
  ne: ID
  eq: ID
  le: ID
  lt: ID
  ge: ID
  gt: ID
  contains: ID
  notContains: ID
  between: [ID]
  beginsWith: ID
  in: [ID]
  notIn: [ID]
}

enum ModelAttributeTypes {
  binary
  binarySet
  bool
  list
  map
  number
  numberSet
  string
  stringSet
  _null
}

input ModelSizeInput {
  ne: Int
  eq: Int
  le: Int
  lt: Int
  ge: Int
  gt: Int
  between: [Int]
}

enum ModelSortDirection {
  ASC
  DESC
}

type ModelHouseholdConnection @aws_iam @aws_cognito_user_pools {
  items: [Household]!
  nextToken: String
}

input ModelHouseholdFilterInput {
  name: ModelStringInput
  owner: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelHouseholdFilterInput]
  or: [ModelHouseholdFilterInput]
  not: ModelHouseholdFilterInput
}

type Query {
  getHousehold(id: ID!): Household @aws_iam @aws_cognito_user_pools
  listHouseholds(filter: ModelHouseholdFilterInput, limit: Int, nextToken: String): ModelHouseholdConnection @aws_iam @aws_cognito_user_pools
  getPerson(id: ID!): Person @aws_iam @aws_cognito_user_pools
  listPeople(filter: ModelPersonFilterInput, limit: Int, nextToken: String): ModelPersonConnection @aws_iam @aws_cognito_user_pools
  getIndicator(id: ID!): Indicator @aws_iam @aws_cognito_user_pools
  listIndicators(filter: ModelIndicatorFilterInput, limit: Int, nextToken: String): ModelIndicatorConnection @aws_iam @aws_cognito_user_pools
  getCheckIn(id: ID!): CheckIn @aws_iam @aws_cognito_user_pools
  listCheckIns(filter: ModelCheckInFilterInput, limit: Int, nextToken: String): ModelCheckInConnection @aws_iam @aws_cognito_user_pools
  getEvent(id: ID!): Event @aws_iam @aws_cognito_user_pools
  listEvents(filter: ModelEventFilterInput, limit: Int, nextToken: String): ModelEventConnection @aws_iam @aws_cognito_user_pools
}

input ModelHouseholdConditionInput {
  name: ModelStringInput
  owner: ModelStringInput
  and: [ModelHouseholdConditionInput]
  or: [ModelHouseholdConditionInput]
  not: ModelHouseholdConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateHouseholdInput {
  name: String!
  owner: String
  id: ID
}

input UpdateHouseholdInput {
  name: String
  owner: String
  id: ID!
}

input DeleteHouseholdInput {
  id: ID!
}

type Mutation {
  createHousehold(input: CreateHouseholdInput!, condition: ModelHouseholdConditionInput): Household @aws_iam @aws_cognito_user_pools
  updateHousehold(input: UpdateHouseholdInput!, condition: ModelHouseholdConditionInput): Household @aws_iam @aws_cognito_user_pools
  deleteHousehold(input: DeleteHouseholdInput!, condition: ModelHouseholdConditionInput): Household @aws_iam @aws_cognito_user_pools
  createPerson(input: CreatePersonInput!, condition: ModelPersonConditionInput): Person @aws_iam @aws_cognito_user_pools
  updatePerson(input: UpdatePersonInput!, condition: ModelPersonConditionInput): Person @aws_iam @aws_cognito_user_pools
  deletePerson(input: DeletePersonInput!, condition: ModelPersonConditionInput): Person @aws_iam @aws_cognito_user_pools
  createIndicator(input: CreateIndicatorInput!, condition: ModelIndicatorConditionInput): Indicator @aws_iam @aws_cognito_user_pools
  updateIndicator(input: UpdateIndicatorInput!, condition: ModelIndicatorConditionInput): Indicator @aws_iam @aws_cognito_user_pools
  deleteIndicator(input: DeleteIndicatorInput!, condition: ModelIndicatorConditionInput): Indicator @aws_iam @aws_cognito_user_pools
  createCheckIn(input: CreateCheckInInput!, condition: ModelCheckInConditionInput): CheckIn @aws_iam @aws_cognito_user_pools
  updateCheckIn(input: UpdateCheckInInput!, condition: ModelCheckInConditionInput): CheckIn @aws_iam @aws_cognito_user_pools
  deleteCheckIn(input: DeleteCheckInInput!, condition: ModelCheckInConditionInput): CheckIn @aws_iam @aws_cognito_user_pools
  createEvent(input: CreateEventInput!, condition: ModelEventConditionInput): Event @aws_iam @aws_cognito_user_pools
  updateEvent(input: UpdateEventInput!, condition: ModelEventConditionInput): Event @aws_iam @aws_cognito_user_pools
  deleteEvent(input: DeleteEventInput!, condition: ModelEventConditionInput): Event @aws_iam @aws_cognito_user_pools
}

input ModelSubscriptionHouseholdFilterInput {
  name: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionHouseholdFilterInput]
  or: [ModelSubscriptionHouseholdFilterInput]
  owner: ModelStringInput
}

type Subscription {
  onCreateHousehold(filter: ModelSubscriptionHouseholdFilterInput, owner: String): Household @aws_subscribe(mutations: ["createHousehold"]) @aws_iam @aws_cognito_user_pools
  onUpdateHousehold(filter: ModelSubscriptionHouseholdFilterInput, owner: String): Household @aws_subscribe(mutations: ["updateHousehold"]) @aws_iam @aws_cognito_user_pools
  onDeleteHousehold(filter: ModelSubscriptionHouseholdFilterInput, owner: String): Household @aws_subscribe(mutations: ["deleteHousehold"]) @aws_iam @aws_cognito_user_pools
  onCreatePerson(filter: ModelSubscriptionPersonFilterInput, owner: String): Person @aws_subscribe(mutations: ["createPerson"]) @aws_iam @aws_cognito_user_pools
  onUpdatePerson(filter: ModelSubscriptionPersonFilterInput, owner: String): Person @aws_subscribe(mutations: ["updatePerson"]) @aws_iam @aws_cognito_user_pools
  onDeletePerson(filter: ModelSubscriptionPersonFilterInput, owner: String): Person @aws_subscribe(mutations: ["deletePerson"]) @aws_iam @aws_cognito_user_pools
  onCreateIndicator(filter: ModelSubscriptionIndicatorFilterInput, owner: String): Indicator @aws_subscribe(mutations: ["createIndicator"]) @aws_iam @aws_cognito_user_pools
  onUpdateIndicator(filter: ModelSubscriptionIndicatorFilterInput, owner: String): Indicator @aws_subscribe(mutations: ["updateIndicator"]) @aws_iam @aws_cognito_user_pools
  onDeleteIndicator(filter: ModelSubscriptionIndicatorFilterInput, owner: String): Indicator @aws_subscribe(mutations: ["deleteIndicator"]) @aws_iam @aws_cognito_user_pools
  onCreateCheckIn(filter: ModelSubscriptionCheckInFilterInput, owner: String): CheckIn @aws_subscribe(mutations: ["createCheckIn"]) @aws_iam @aws_cognito_user_pools
  onUpdateCheckIn(filter: ModelSubscriptionCheckInFilterInput, owner: String): CheckIn @aws_subscribe(mutations: ["updateCheckIn"]) @aws_iam @aws_cognito_user_pools
  onDeleteCheckIn(filter: ModelSubscriptionCheckInFilterInput, owner: String): CheckIn @aws_subscribe(mutations: ["deleteCheckIn"]) @aws_iam @aws_cognito_user_pools
  onCreateEvent(filter: ModelSubscriptionEventFilterInput, owner: String): Event @aws_subscribe(mutations: ["createEvent"]) @aws_iam @aws_cognito_user_pools
  onUpdateEvent(filter: ModelSubscriptionEventFilterInput, owner: String): Event @aws_subscribe(mutations: ["updateEvent"]) @aws_iam @aws_cognito_user_pools
  onDeleteEvent(filter: ModelSubscriptionEventFilterInput, owner: String): Event @aws_subscribe(mutations: ["deleteEvent"]) @aws_iam @aws_cognito_user_pools
}

type ModelPersonConnection @aws_iam @aws_cognito_user_pools {
  items: [Person]!
  nextToken: String
}

input ModelPersonRoleInput {
  eq: PersonRole
  ne: PersonRole
}

input ModelPersonFilterInput {
  householdId: ModelIDInput
  owner: ModelStringInput
  displayName: ModelStringInput
  role: ModelPersonRoleInput
  avatarUrl: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelPersonFilterInput]
  or: [ModelPersonFilterInput]
  not: ModelPersonFilterInput
}

input ModelPersonConditionInput {
  householdId: ModelIDInput
  owner: ModelStringInput
  displayName: ModelStringInput
  role: ModelPersonRoleInput
  avatarUrl: ModelStringInput
  and: [ModelPersonConditionInput]
  or: [ModelPersonConditionInput]
  not: ModelPersonConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreatePersonInput {
  householdId: ID!
  owner: String
  displayName: String!
  role: PersonRole
  avatarUrl: String
  id: ID
}

input UpdatePersonInput {
  householdId: ID
  owner: String
  displayName: String
  role: PersonRole
  avatarUrl: String
  id: ID!
}

input DeletePersonInput {
  id: ID!
}

input ModelSubscriptionPersonFilterInput {
  householdId: ModelSubscriptionIDInput
  displayName: ModelSubscriptionStringInput
  role: ModelSubscriptionStringInput
  avatarUrl: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionPersonFilterInput]
  or: [ModelSubscriptionPersonFilterInput]
  owner: ModelStringInput
}

type ModelIndicatorConnection @aws_iam @aws_cognito_user_pools {
  items: [Indicator]!
  nextToken: String
}

input ModelIndicatorPolarityInput {
  eq: IndicatorPolarity
  ne: IndicatorPolarity
}

input ModelIndicatorInputTypeInput {
  eq: IndicatorInputType
  ne: IndicatorInputType
}

input ModelIndicatorFilterInput {
  personId: ModelIDInput
  owner: ModelStringInput
  name: ModelStringInput
  questionText: ModelStringInput
  polarity: ModelIndicatorPolarityInput
  inputType: ModelIndicatorInputTypeInput
  active: ModelBooleanInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelIndicatorFilterInput]
  or: [ModelIndicatorFilterInput]
  not: ModelIndicatorFilterInput
}

input ModelIndicatorConditionInput {
  personId: ModelIDInput
  owner: ModelStringInput
  name: ModelStringInput
  questionText: ModelStringInput
  polarity: ModelIndicatorPolarityInput
  inputType: ModelIndicatorInputTypeInput
  active: ModelBooleanInput
  and: [ModelIndicatorConditionInput]
  or: [ModelIndicatorConditionInput]
  not: ModelIndicatorConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateIndicatorInput {
  personId: ID!
  owner: String
  name: String!
  questionText: String
  polarity: IndicatorPolarity
  inputType: IndicatorInputType
  active: Boolean
  id: ID
}

input UpdateIndicatorInput {
  personId: ID
  owner: String
  name: String
  questionText: String
  polarity: IndicatorPolarity
  inputType: IndicatorInputType
  active: Boolean
  id: ID!
}

input DeleteIndicatorInput {
  id: ID!
}

input ModelSubscriptionIndicatorFilterInput {
  personId: ModelSubscriptionIDInput
  name: ModelSubscriptionStringInput
  questionText: ModelSubscriptionStringInput
  polarity: ModelSubscriptionStringInput
  inputType: ModelSubscriptionStringInput
  active: ModelSubscriptionBooleanInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionIndicatorFilterInput]
  or: [ModelSubscriptionIndicatorFilterInput]
  owner: ModelStringInput
}

type ModelCheckInConnection @aws_iam @aws_cognito_user_pools {
  items: [CheckIn]!
  nextToken: String
}

input ModelCheckInFilterInput {
  personId: ModelIDInput
  owner: ModelStringInput
  occurredAt: ModelStringInput
  answersJson: ModelStringInput
  note: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelCheckInFilterInput]
  or: [ModelCheckInFilterInput]
  not: ModelCheckInFilterInput
}

input ModelCheckInConditionInput {
  personId: ModelIDInput
  owner: ModelStringInput
  occurredAt: ModelStringInput
  answersJson: ModelStringInput
  note: ModelStringInput
  and: [ModelCheckInConditionInput]
  or: [ModelCheckInConditionInput]
  not: ModelCheckInConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateCheckInInput {
  personId: ID!
  owner: String
  occurredAt: AWSDateTime!
  answersJson: AWSJSON
  note: String
  id: ID
}

input UpdateCheckInInput {
  personId: ID
  owner: String
  occurredAt: AWSDateTime
  answersJson: AWSJSON
  note: String
  id: ID!
}

input DeleteCheckInInput {
  id: ID!
}

input ModelSubscriptionCheckInFilterInput {
  personId: ModelSubscriptionIDInput
  occurredAt: ModelSubscriptionStringInput
  answersJson: ModelSubscriptionStringInput
  note: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionCheckInFilterInput]
  or: [ModelSubscriptionCheckInFilterInput]
  owner: ModelStringInput
}

type ModelEventConnection @aws_iam @aws_cognito_user_pools {
  items: [Event]!
  nextToken: String
}

input ModelEventTypeInput {
  eq: EventType
  ne: EventType
}

input ModelEventFilterInput {
  personId: ModelIDInput
  owner: ModelStringInput
  occurredAt: ModelStringInput
  type: ModelEventTypeInput
  title: ModelStringInput
  description: ModelStringInput
  metadataJson: ModelStringInput
  id: ModelIDInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
  and: [ModelEventFilterInput]
  or: [ModelEventFilterInput]
  not: ModelEventFilterInput
}

input ModelEventConditionInput {
  personId: ModelIDInput
  owner: ModelStringInput
  occurredAt: ModelStringInput
  type: ModelEventTypeInput
  title: ModelStringInput
  description: ModelStringInput
  metadataJson: ModelStringInput
  and: [ModelEventConditionInput]
  or: [ModelEventConditionInput]
  not: ModelEventConditionInput
  createdAt: ModelStringInput
  updatedAt: ModelStringInput
}

input CreateEventInput {
  personId: ID!
  owner: String
  occurredAt: AWSDateTime!
  type: EventType
  title: String!
  description: String
  metadataJson: AWSJSON
  id: ID
}

input UpdateEventInput {
  personId: ID
  owner: String
  occurredAt: AWSDateTime
  type: EventType
  title: String
  description: String
  metadataJson: AWSJSON
  id: ID!
}

input DeleteEventInput {
  id: ID!
}

input ModelSubscriptionEventFilterInput {
  personId: ModelSubscriptionIDInput
  occurredAt: ModelSubscriptionStringInput
  type: ModelSubscriptionStringInput
  title: ModelSubscriptionStringInput
  description: ModelSubscriptionStringInput
  metadataJson: ModelSubscriptionStringInput
  id: ModelSubscriptionIDInput
  createdAt: ModelSubscriptionStringInput
  updatedAt: ModelSubscriptionStringInput
  and: [ModelSubscriptionEventFilterInput]
  or: [ModelSubscriptionEventFilterInput]
  owner: ModelStringInput
}
